services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/shade-agent-template:latest@sha256:d44cefb792c77a89b55f7da439d7c514120f869aafc9ecee2cb6c4c559558238
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
